### ISSUE TITLE
Inline SVG Rendering Issue

### ISSUE THREAD

**Issue by Notplayingallday383** [MercuryWorkshop/dreamlandjs#2]
So I pinged this in the discord earlier, However if you missed it its also here. So basically the "fix" to inline SVG rendering did not fix it and ended up breaking it as seen in the video below: 
https://github.com/MercuryWorkshop/dreamlandjs/assets/72810050/3ecf0ba2-62b2-475f-b099-c951c75dbc54

Steps to reproduce: 
- Create a new TSX File and put a Inline SVG in it. for example: percury.svg's inline svg content
- Start the HTTP Server and watch

At the moment untill this is resolved im using the defualt version from earlier

**Comment by CoolElectronics** [comment]
fixed in [066d6e7](https://github.com/MercuryWorkshop/dreamlandjs/commit/066d6e70ebb48cb953ab823e52935814451e3884)
