### ISSUE TITLE
Feature request: ES6 module build

### ISSUE THREAD

**Issue by cebaa** [MercuryWorkshop/dreamlandjs#8]
It would be great to add an ES6 module build to avoid polluting global `window`.

**Comment by velzie** [comment]
Thanks for your interest! I don't think it's possible to avoid the pollution of window, the `use` function powering stateful is based on a global getter. Since at least two of the functions would always have to be global i'm not sure an es6 module is worth it and could lead to other issues like duplicate instances of dreamland running at the same time

**Comment by cebaa** [comment]
Does it have to be global on `window` or could it be set on some other object?

Like what would be the problems with something like this?

```
import dreamlandFactory from 'dreamland'

// dreamlandFactory sets whatever is set on window currently on the provided object instead and returns that object
const { h, html, use } = dreamlandFactory({})

function App() {
  this.counter = 0
  return html`
    <div>
      <button on:click=${() => this.counter++}>Click me!</button>
      <p>${use(this.counter)}</p>
    </div>
  `
}

document.body.appendChild(h(App))
```

If making sure only one dreamland instance exists is important, users can opt to simulate the current behavor with:

```
dreamlandFactory(window)
```

to set things on `window` by default. Or perhaps do their own:

```
if(!window.__dreamlandInstance) {
  window.__dreamlandInstance = dreamlandFactory({})
}
```

Would that not work for some reason?

**Comment by velzie** [comment]
No, a configuration like that would not work. The getter for use would get called only once during the destructuring and then state would not work for the rest of the app.

You would have to access the properties like
```
import dreamlandFactory from 'dreamland'

const  dream = dreamlandFactory({})

function App() {
  this.counter = 0
  return dream.html`
    <div>
      <button on:click=${() => this.counter++}>Click me!</button>
      <p>${dream.use(this.counter)}</p>
    </div>
  `
}

document.body.appendChild(dream.h(App))
```

I don't like how this syntax looks, and all existing libraries/apps are already built around the assumption that the globals are available

**Comment by cebaa** [comment]
Thanks, closing this then!
